[workspace]
members = ["geoserde"]

[package]
name = "fgbfile"
version = "0.3.2"
edition = "2021"
description = "Easily write local FlatGeobuf files."
repository = "https://github.com/p4ken/fgbfile"
license = "MIT"
exclude = [".*"]

[dependencies]
flatgeobuf = { version = "3.27.0", default-features = false }
geo-types = { version = "0.7.11", features = ["serde"] }
geoserde = { version = "0.1.0", path = "geoserde", default-features = false }
serde = "1.0.193"

[dev-dependencies]
anyhow = "1.0.75"
