[package]
name = "geoserde"
version = "0.2.2"
edition = "2021"
description = "serializer and deserislizer for geospatial data"
repository = "https://github.com/p4ken/geoserde"
license = "MIT"
exclude = [".*"]

[features]
geozero = ["dep:geozero"]
default = ["geozero"]

[dependencies]
geo-types = { version = "0.7.11" }
serde = { version = "1.0.188" }
geozero = { version = "0.11.0", optional = true }

[dev-dependencies]
geo-types = { version = "0.7.11", features = ["serde"] }
serde = { version = "1.0.188", features = ["derive"] }
anyhow = { version = "1.0.75", features = ["backtrace"] }
flatgeobuf = { version = "4.0.0", default-features = false }
