[package]
name = "geoserde"
version = "0.1.0"
edition = "2021"

[dependencies]
geo-types = { version = "0.7.11", features = ["serde"] }
serde = { version = "1.0.188", features = ["derive"] }
geozero = "0.11.0"
